// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKul6mkyx0LfpgMbXSMBP-r9swxWDqgYc',
    appId: '1:263141358051:web:9250b0c830d4d883cd48d6',
    messagingSenderId: '263141358051',
    projectId: 'movieappt2',
    authDomain: 'movieappt2.firebaseapp.com',
    storageBucket: 'movieappt2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzcWudotNgrRea35vUNoi2pmn4GgyK8w',
    appId: '1:263141358051:android:3f0861f1e532f173cd48d6',
    messagingSenderId: '263141358051',
    projectId: 'movieappt2',
    storageBucket: 'movieappt2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCRDJoyjcV4nkjxFWwPs9uWaFhfEsHGu8',
    appId: '1:263141358051:ios:846bb69ddd865a6acd48d6',
    messagingSenderId: '263141358051',
    projectId: 'movieappt2',
    storageBucket: 'movieappt2.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCRDJoyjcV4nkjxFWwPs9uWaFhfEsHGu8',
    appId: '1:263141358051:ios:a5e0ea499333d56ecd48d6',
    messagingSenderId: '263141358051',
    projectId: 'movieappt2',
    storageBucket: 'movieappt2.appspot.com',
    iosBundleId: 'com.example.movie.RunnerTests',
  );
}
